name: GATE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Bazelisk
        run: |
          curl -LO https://github.com/bazelbuild/bazelisk/releases/download/v1.29.0/bazelisk-linux-amd64
          mkdir -p "${GITHUB_WORKSPACE}/bin"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - run: bazel run //tools/format
      - run: bazel build //src/main:LibraryManagementSystem --config=lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - uses: actions/checkout@v6
      - name: Install Bazelisk
        run: |
          curl -LO https://github.com/bazelbuild/bazelisk/releases/download/v1.29.0/bazelisk-linux-amd64
          mkdir -p "${GITHUB_WORKSPACE}/bin"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Test
        run: bazel test //...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - name: Install Bazelisk
        run: |
          curl -LO https://github.com/bazelbuild/bazelisk/releases/download/v1.29.0/bazelisk-linux-amd64
          mkdir -p "${GITHUB_WORKSPACE}/bin"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - run: bazel build //src/main:LibraryManagementSystem